[package]
name = "warp-sudoku-solver"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
warp = "0.2"
tokio ={version = "0.2", features = ["macros"]} 
serde_json = "1"
serde = {version = "1", features = ['derive']}

[profile.release]
lto = true 
codegen-units = 1